### ISSUE TITLE
.python-version conflict

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/standard_profile_template#61]
I use pyenv and pyenv-virtualenv to manage my Python environments so my local copy of the OC4IDS repository has a (not checked-in) `.python-version` file pointing to a virtual environment named 'infrastructure'. When trying to pull updates from remote, the `.python-version`  file added in https://github.com/open-contracting/infrastructure/commit/2f49cd9955d7afa14bb9333bc01f3a8245b181bb conflicts with my local file. It points to an environment named 3.10, which doesn't exist on my system.

If I correctly understood how pyenv and pyenv-virtualenv work, I think this might cause problems because multiple profiles might end up installing potentially conflicting dependencies into the same environment ('3.10'). I prefer to keep a 'clean' environment for each Python version I need to work with (e.g. '3.10') and, from that, create a separate virtual environment for each project that uses that version of Python (e.g. 'infrastructure').

**Comment by jpmckinney** [comment]
`.python-version` just says what Python version (not virtualenv) to use.

When using pyenv, my process was to do `pyenv activate myvenv`. I didn't rely on any automatic venv selection – not exactly sure what's happening in your case. Anyway, just use `pyenv activate` to select the venv you want. So:

```
pyenv virtualenv 3.10.15 infrastructure
pyenv activate infrastructure
```

FWIW, we use [uv](https://github.com/astral-sh/uv) now.

**Comment by duncandewhurst** [comment]
I'm using the pyenv-virtualenv plugin, which automatically activates and deactivates virtual environments when entering/leaving directories that contain a `.python-version` file.

I'll take a look at uv, thanks for the tip.

**Comment by jpmckinney** [comment]
Aha. Yeah pyenv-virtualenv seems to use .python-version for a different purpose that the rest of the ecosystem. Even pyenv (on its own without pyenv-virtualenv) treats .python-version as the Python version to use (not the virtualenv to activate).
